
# Nombre del workflow
name: Ejemplo

# Cuando se va a ajecutar este workflow
on: [push]

# La sintaxis cuando se ejecuta el workflow
jobs:
  Ejemplo:
    runs-on: ubuntu-latest
    steps:
    - name: Maven Dependency Tree Dependency Submission
      # You may pin to the exact commit or the version.
      # uses: advanced-security/maven-dependency-submission-action@2ecce44ccb44fd4b52f43468d3644e2d3e2b3cf2
      uses: advanced-security/maven-dependency-submission-action@v2.0.1
      with:
        # The GitHub token to use to submit the depedency snapshot to the repository
        token: ${{ github.token }}
